name: Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  trivy:
    name: Vulnerability scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@e368e328979b113139d6f9068e03accaed98a518
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
